### ISSUE TITLE
Plugin update: Support new version of Django (Pylint)

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#103]
<p>Our current version of Pylint only supports django 1.9.2.  (<a href="https://github.com/codacy/codacy-pylint/blob/master/build.sbt#L36" class="external-link" rel="nofollow">https://github.com/codacy/codacy-pylint/blob/master/build.sbt#L36</a>)</p>

<p>Please add support to the most recent version of django</p>

gz#2540

**Comment by mrfyda** [comment]
Fixed in #88

**Comment by lolgab** [comment]
I'll close it when we have Pylint 2.3.1 in production.
