### ISSUE TITLE
Update Sonar C# to 7.16

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#106]
- We have multiple customers and potential customers requesting Sonar C# update.
- A client is reporting that we are only showing 223 patterns when the most recent version of the tool has 330. Also, the client is asking for a config file support that we do not have at the moment.

gz#2422

gz#2427

gz#2530

gz#7150

gz#7269

gz#7343

gz#7362

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/2422'>Zendesk ticket #2422</a>:<br><br>Hi Damien,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/106.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/2427'>Zendesk ticket #2427</a>:<br><br>Hi Oleg,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/106.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7150'>Zendesk ticket #7150</a>:<br><br>Hi Ivo,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/106.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7269'>Zendesk ticket #7269</a>:<br><br>Hi Jeff,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/106.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7343'>Zendesk ticket #7343</a>:<br><br>Hi James,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/106.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7362'>Zendesk ticket #7362</a>:<br><br>Hi Jon,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/106.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by Laracodacy** [comment]
This item is the same as https://github.com/codacy/codacy-sonar-csharp/issues/3. We are not closing it as it is attached with many user reports. But they should be closed simultaneously.
