### ISSUE TITLE
Make PMD 6 default and remove Legacy PMD as default

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#135]
<p>After implementing 
    <span class="jira-issue-macro" data-jira-key="FT-3904" >
                <a href="https://codacy.atlassian.net/browse/FT-3904" class="jira-issue-macro-key issue-link"  title="Handle multiple engines versions and plugins" >
            <img class="icon" src="https://codacy.atlassian.net/secure/viewavatar?size=medium&avatarId=10307&avatarType=issuetype" />
            FT-3904
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-complete jira-macro-single-issue-export-pdf">To Do</span>
            </span>
 we should update PMD to be the new default.</p>

We still have PMD Legacy as the default tool. We should change to have PMD 6 as the default tool.

**Comment by Laracodacy** [comment]
Lets sync back with Success Team once this is tackled.
