### ISSUE TITLE
Sonar C# analyer throws this error:

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#155]
Sonar C# is trowing this error:

Docker exited with code 1
stdout:
stderr: WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Error executing the tool
java.lang.Exception:
Failed to run Sonar C#
SonarAnalyzer for C# version 5.10.1.1411

 gz#7483

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7483'>Zendesk ticket #7483</a>:<br><br>Hi Ryan,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/155.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by Laracodacy** [comment]
Once we complete Sonar C# update to version 7.x.x - lets check if this problem still remains.

**Comment by ljmf00** [comment]
This issue will be closed due to breaking updates on the tool and major updates.
