### ISSUE TITLE
[CY-2386] Discussion: Dropping sbt-native-packager and using Docker directly

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#161]
## Status quo
- We are using the sbt-native-packager plugins for almost every tool written in Scala.
## Advantages
It let us control the creation and the publishing of docker images directly from sbt. 👍 
## Disadvantages
- sbt-native-packager has not a nice semantic versioning strategy.
- Updating minor versions breaks the build.
- Tries to hide DockerFile complexity, creating other complexity when you need custom docker settings.

For example, this is a generated DockerFile:
```dockerfile
FROM library/openjdk:8-jre-alpine
LABEL MAINTAINER="Rodrigo Fernandes <rodrigo@codacy.com>"
WORKDIR /opt/docker
RUN adduser -u 2004 -D docker
ENV TOOL_VERSION 10.1.0
ENV STYLELINT_CONFIG_BASEDIR /usr/lib/node_modules
ADD --chown=docker:docker opt /opt
RUN apk update && apk add bash curl npm && ./install.sh |rm -rf /tmp/* && rm -rf /var/cache/apk/* rm ./install.sh
RUN mv /opt/docker/docs /docs
RUN ["chown", "-R", "docker:docker", "/docs"]
ENV NODE_PATH /usr/lib/node_modules
USER docker
ENTRYPOINT ["/opt/docker/bin/codacy-stylelint"]
CMD []
``` 
and these are sbt settings to generate it:
```scala
def installAll() =
  s"""apk update &&
     |apk add bash curl npm &&
     |./install.sh
     ||rm -rf /tmp/* &&
     |rm -rf /var/cache/apk/*
     |rm ./install.sh""".stripMargin.replaceAll(System.lineSeparator(), " ")

val defaultDockerInstallationPath = "/opt/docker"
packageName in Docker := name.value
version in Docker := version.value
maintainer in Docker := "Rodrigo Fernandes <rodrigo@codacy.com>"
dockerBaseImage := "library/openjdk:8-jre-alpine"
dockerUpdateLatest := true
defaultLinuxInstallLocation in Docker := defaultDockerInstallationPath
daemonUser in Docker := "docker"
daemonGroup in Docker := "docker"
dockerEntrypoint := Seq(s"$defaultDockerInstallationPath/bin/${name.value}")
dockerCmd := Seq()
dockerCommands := dockerCommands.value.flatMap {
  case cmd @ Cmd("ADD", _) =>
    List(
      Cmd("RUN", "adduser -u 2004 -D docker"),
      Cmd("ENV", s"TOOL_VERSION ${toolVersion.value}"),
      Cmd("ENV", s"STYLELINT_CONFIG_BASEDIR /usr/lib/node_modules"),
      cmd,
      Cmd("RUN", installAll()),
      Cmd("RUN", "mv /opt/docker/docs /docs"),
      ExecCmd("RUN", Seq("chown", "-R", s"docker:docker", "/docs"): _*),
      Cmd("ENV", "NODE_PATH /usr/lib/node_modules")
    )
  case other => List(other)
}
```
It seems, more and less, that the maintenance cost is almost the same. 
By the way there is a lot more documentation about editing Dockerfiles than sbt-native-packager sbt settings, and we are sure that updating from version `1.3.15` to `1.3.16` doesn't change completely our dockerfiles.

## Replacing docker:publishXYZ commands
We need to investigate what's the best substitute to `docker:publish` and `docker:publishLocal` sbt commands. They could be some sort of bash scripts or some sbt simple tasks (maybe shared as a little sbt plugin).
We could also investigate if could be useful using sbt-native-packager with custom Dockerfiles bypassing its Dockerfile generation at all.

**Comment by mrfyda** [comment]
@lolgab what is preventing you from making a decision here?
