### ISSUE TITLE
Hello, I was just pushed a new docker image for PowerShell la

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#174]
Update is for PSScriptAnalyzer engine. The repo for the engine is at: https://github.com/codacy/codacy-psscriptanalyzer
The updated dockerfile is at: https://github.com/adityapatwardhan/ps-codacy/blob/master/Dockerfile

gz#7634

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7634'>Zendesk ticket #7634</a>:<br><br>Hi Aditya,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/174.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by mrfyda** [comment]
@IGFCoimbra can you request that this is made through a pull request to the repo?
