### ISSUE TITLE
update the detekt plugin to 1.0.0-RC16

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#175]
update the detekt plugin to 1.0.0-RC16<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/7626'>Zendesk ticket #7626</a>)<br>gz#7626</i>

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7626'>Zendesk ticket #7626</a>:<br><br>Hi Miguel,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/175.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by lolgab** [comment]
Public comment from Miguel Panelo in <a href='https://codacy.zendesk.com/agent/tickets/7626'>Zendesk ticket #7626</a>:<br><br>Hey Ivo,

Is the repository for updating detekt open source? I can also create a PR just to update the plugin.

**Comment by gjsduarte** [comment]
Superseded by https://github.com/codacy/codacy-detekt/issues/13
