### ISSUE TITLE
Add support for golangci-lint

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#176]
This tool helps catch more issues than go vet and go lint. 

https://github.com/golangci/golangci-lint<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/7651'>Zendesk ticket #7651</a>)<br>gz#7651</i>

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7720'>Zendesk ticket #7720</a>:<br><br>Hi Carl,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/176.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by mrfyda** [comment]
Won't be tackled right now.
Moved to productboard.
