### ISSUE TITLE
[CY-2394] Default patterns for Shellcheck

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#188]
shellcheck.net seems to be using a different set of default patterns than Codacy. 

A user is requesting that the default patterns being used on Codacy to be updated following the tools onw default. <br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/7771'>Zendesk ticket #7771</a>)<br>gz#7771</i>

**Comment by mrfyda** [comment]
@lolgab Default patterns are manual and defined outside the tool wrappers.
Ideally, we could define a way to include this in the tools specification and automate it!

**Comment by Kreyren** [comment]
Notice: I created the request #7771 on codacy

My experience was that Codacy doesn't catch anything in comparison to shellcheck.net and i had to spent +- 30~50mins cherrypicking patterns for https://github.com/ohmybash/oh-my-bash which was and is pita and chosing `all` option is insane assuming outdated patterns to catch shellcheck issues alike (https://github.com/koalaman/shellcheck/wiki/SC1072):
![image](https://user-images.githubusercontent.com/11302521/63429539-da6f7c80-c409-11e9-9325-3b4d7b36b17c.png)

if i could chose patterns from shellcheck.net the whole process would be much faster.

Fixes: https://github.com/ohmybash/oh-my-bash/issues/83
Bug: https://github.com/koalaman/shellcheck/issues/1675
