### ISSUE TITLE
Prevent non-Codacy users from editing codacy wikis

### ISSUE THREAD

**Issue by mrfyda** [codacy/codacy-meta#189]
Some GitHub repos allow anyone to edit Wiki pages.

1. Go to https://github.com/codacy/akka-typed/wiki
2. Any GitHub user can edit this page

Links to all vulnerable projects of Codacy:

- https://github.com/codacy/akka-typed
- https://github.com/codacy/aws-dynamodb-local
- https://github.com/codacy/codacy-brakeman
- https://github.com/codacy/codacy-coffeelint
- https://github.com/codacy/codacy-cppcheck
- https://github.com/codacy/codacy-jshint
- https://github.com/codacy/codacy-phpmd
- https://github.com/codacy/codacy-pylint
- https://github.com/codacy/codacy-staticcheck
- https://github.com/codacy/codacy-veraxx
- https://github.com/codacy/php-codacy-coverage
- https://github.com/codacy/python-codacy-coverage
- https://github.com/codacy/readme-badger
- https://github.com/codacy/sbt-codacy-coverage
- https://github.com/codacy/scalastyle
- https://github.com/codacy/stash-scala-client
- https://github.com/codacy/teamcity-docker-agent
- https://github.com/codacy/test
- https://github.com/codacy/ubuntu-jdk8

**Comment by lolgab** [comment]
Wikis theirselves are meant to work this way: 
<img width="766" alt="Wiki settings" src="https://user-images.githubusercontent.com/5793054/63697988-d9798900-c815-11e9-9839-1b14aa515713.png">
So I'm going to deactivate wiki for all out projects if we don't want them to be editable.

**Comment by mrfyda** [comment]
There is an option that allows only for organization members to edit them.
We might want to keep existing wikis with that setting.

**Comment by lolgab** [comment]
We don't seem to have actual wikis with content in them.
