### ISSUE TITLE
typescript-eslint will replace TSLint

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#190]
typescript-eslint will replace TSLint according to https://eslint.org/blog/2019/01/future-typescript-eslint

typescript-eslint can be found at  https://github.com/typescript-eslint/typescript-eslint<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/7838'>Zendesk ticket #7838</a>)<br>gz#7838</i>

**Comment by mrfyda** [comment]
typescript-eslint has been added to codacy-eslint
