### ISSUE TITLE
Failed to do code review on pull request updated by Mergify bot

### ISSUE THREAD

**Issue by Hongbo-Miao** [codacy/codacy-meta#194]
I have this pull request https://github.com/Hongbo-Miao/hongbomiao.com/pull/165

Mergify bot auto pull from latest master branch because another pull request just merged to master.

Codacy failed to do code review on this pull request and shows this error

> We couldn't analyze this commit from mergify[bot] because it's not associated with a valid e-mail (37929162+mergify[bot]@users.noreply.github.com).

![image](https://user-images.githubusercontent.com/3375461/63838385-1e92dd80-c932-11e9-9df6-7d7d7702a110.png)

at here https://app.codacy.com/app/Hongbo-Miao/hongbomiao.com/pullRequest?prid=4073668

I am sure there is a reason for Codacy team to choose to verify email first, however I am aiming to use Codacy to review all pull requests not just by human but also by bots.

It would be great to add option to skip email checking for those bots' pull requests. Thanks

**Comment by mrfyda** [comment]
Thank you for your feedback. 🙌

This is something we are working on outside the scope of @codacy/toss, meaning that it's being tracked internal and you won't be able to see progress on GitHub.
I'll come back and update this issue when the feature is available!
