### ISSUE TITLE
Sometimes Codacy is slow picking up the pull request

### ISSUE THREAD

**Issue by Hongbo-Miao** [codacy/codacy-meta#195]
Most time Codacy can start code review immediately, but sometimes it takes very long time for Codacy to pick up pull request and do code review.

When that happens, tt also does not show in my Codacy pull request list:
https://app.codacy.com/app/Hongbo-Miao/hongbomiao.com/pullRequests

For example, this pull request https://github.com/Hongbo-Miao/hongbomiao.com/pull/148
It takes two hours for Codacy to respond and start the code review.

**Comment by mrfyda** [comment]
Hi @Hongbo-Miao 

We have released major infrastructure changes to address this issue.
If you keep encountering this let us know!

Closing for now.

**Comment by Hongbo-Miao** [comment]
Got it, thanks!
