### ISSUE TITLE
Investigate further SQL support

### ISSUE THREAD

**Issue by mrfyda** [codacy/codacy-meta#199]
Investigate options to expand our current ANSI SQL support with more rules.

The investigation should result in a list of possible tools to be adopted with the following criteria: rules (number and kind), license, tool requirements (compilation, database connection), updates frequency, flavours (ANSI, PL/SQL, etc).

Rules should focus on:
* Performance (e.g. don't use `cross join`s)
* Best practices (e.g. close `cursor` after usage)
* Logic (e.g. contradictory `where` clauses)

Rules shouldn't focus on:
* Code style (e.g. indentation)
* Syntax (e.g. compilation errors)

**Comment by lolgab** [comment]
I'm closing this for now.
