### ISSUE TITLE
Update Go support

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#214]
Update Go support

<i>(created from <a href='https://codacy.zendesk.com/agent/tickets/8128'>Zendesk ticket #8128</a>)<br>gz#8128</i>

**Comment by tobiassjosten** [comment]
Is this fixed, then? 😄

**Comment by lolgab** [comment]
No, just treated in another ticket #242
We had duplicated issues on Github and we are trying to clean-up our backlog :)
