### ISSUE TITLE
RemarkLint default patterns generating contradictories reports 

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#224]
After the update on the version of RemarkLint we support, two of the tool's default patterns started generating contradictories reports.

The "Warn when list item bullets are indented"  will ask the user to remove the spaces and  "Warn when the list item marker style of ordered lists violate a given style" will ask the user to add the spaces.

We should remove on of those from the default pattern list<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/8327'>Zendesk ticket #8327</a>)<br>gz#8327</i>

**Comment by mrfyda** [comment]
The default patterns no longer enforce contradictory patterns.
