### ISSUE TITLE
Add-ons for cppcheck

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#230]
Add support for https://github.com/danmar/cppcheck/tree/master/addons<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/8417'>Zendesk ticket #8417</a>)<br>gz#8417</i>

**Comment by ljmf00** [comment]
Addons to add:

- [ ] cert
- [ ] y2038
- [ ] threadsafety
- [ ] misra

**Comment by lolgab** [comment]
We have already added three of the four addons available for cppcheck.
Now we only miss misra addon to close this issue.
