### ISSUE TITLE
Add support for eslint-plugin-m6web-i18n

### ISSUE THREAD

**Issue by bignimbus** [codacy/codacy-meta#243]
https://github.com/M6Web/eslint-plugin-m6web-i18n

This plugin has a few rules for linting various i18n issues inside react components.  It would be great to be able to use these rules in codacy.  Thank you for the great tool!

**Comment by lolgab** [comment]
Hi @bignimbus,
We added the plugin and now it's merged on master. We will close this issue when it will be running in production.
Lorenzo

**Comment by bignimbus** [comment]
Thank you @lolgab!

**Comment by lolgab** [comment]
Hi @bignimbus,
I confirm that the new update is running in production.
We couldn't, however, add it to the UI configuration since it needs some special settings that we couldn't give through the UI.
So you'll need to use it with a custom configuration file.
Thank you for letting use notice.
Lorenzo
