### ISSUE TITLE
Deprecate language specific coverage reporters and fix multilanguage coverage reporter documentation

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#248]
- Update Codacy documentation removing the links to language specific coverage reporters
    - https://support.codacy.com/hc/en-us/articles/207312879-Generate-Coverage
    - https://support.codacy.com/hc/en-us/articles/207279819-Coverage
    - https://support.codacy.com/hc/en-us/articles/207993835-Add-coverage-to-your-repo
- Raise coverage-parser
- Bump coverage-parser version in codacy-coverage-reporter
- Raise codacy-coverage-reporter
- Update codacy-coverage-reporter and coverage-parser documentation
    - Add How-to explanation for each tool
    - [Optional] Add example project for each tool (e.g., how to integrate with CircleCI)
- Add a deprecation message on other reporters repos

**Comment by mrfyda** [comment]
There is also this in-app page that links to every supported reported:
https://app.codacy.com/gh/codacy/codacy-coverage-reporter/settings/coverage
