### ISSUE TITLE
Move tools to new TIMEOUT_SECONDS environment variable

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#250]
**Duplication**
Scala Tools should only use a version of `codacy-duplication-scala-seed` >= `2.0.1` to use the new env variable
- [x] C#
- [x] C
- [x] C++
- [x] Go
- [x] Java
- [x] Javascript
- [x] PHP
- [x] Python
- [x] Ruby
- [x] Scala
- [x] Swift

**Metrics**

Scala Tools should only use a version of `codacy-metrics-scala-seed` >= `0.2.2` to use the new env variable

- [x] cloc https://github.com/codacy/codacy-metrics-cloc/pull/20
- [x] ESLint
- [x] GoCyclo https://github.com/codacy/codacy-metrics-gocyclo/pull/10
- [x] Pdepend
- [x] PMD https://github.com/codacy/codacy-metrics-pmd/pull/6
- [x] Radon https://github.com/codacy/codacy-metrics-radon/pull/6
- [x] RuboCop https://github.com/codacy/codacy-metrics-rubocop/pull/8
- [x] ScalaMeta https://github.com/codacy/codacy-metrics-scala/pull/6
- [x] ScalaStyle https://github.com/codacy/codacy-metrics-scalastyle/pull/10
- [x] Sonar C# https://github.com/codacy/codacy-metrics-sonar-csharp/pull/19

**Results**

Scala Tools should only use a version of `codacy-engine-scala-seed` >= `3.1.1` to use the new env variable

- [x] ~~Ameba~~ **Doesn't support timeout**
- [x] Bandit
- [x] Brakeman
- [x] ~~BundlerAudit~~ **Doesn't support timeout**
- [x] Checkstyle
- [x] Codacy ScalaMeta Pro https://github.com/codacy/codacy-scalameta/pull/61
- [x] ~~CoffeeLint~~ **Doesn't support timeout**
- [x] cppcheck https://github.com/codacy/codacy-cppcheck/pull/39
- [x] ~~credo~~ **Doesn't support timeout**
- [x] CSSLint https://github.com/codacy/codacy-csslint/pull/11
- [x] Detekt https://github.com/codacy/codacy-detekt/pull/29
- [x] ESLint https://github.com/codacy/codacy-eslint/pull/132
- [x] Spotbugs
- [x] Flawfinder
- [x] ~~Hadolint~~ **Doesn't support timeout**
- [x] JacksonLinter https://github.com/codacy/codacy-jackson-linter/pull/13
- [x] JSHint https://github.com/codacy/codacy-jshint/pull/20/files
- [x] PHP CodeSniffer
- [x] PHP MessDetector
- [x] PMD
- [x] Prospector
- [x] ~~PSScriptAnalyzer~~ **Doesn't support timeout**
- [x] PyLint Legacy https://github.com/codacy/codacy-pylint/pull/57
- [x] PyLint (Python 3) https://github.com/codacy/codacy-pylint-python3/pull/28
- [x] ~~RemarkLint~~ **Doesn't support timeout**
- [x] Rubocop https://github.com/codacy/codacy-rubocop/pull/67
- [x] ScalaStyle https://github.com/codacy/codacy-scalastyle/pull/22
- [x] shellcheck
- [x] Sonar C# https://github.com/codacy/codacy-sonar-csharp/pull/36
- [x] SQLint https://github.com/codacy/codacy-sqlint/pull/11
- [x] Stylelint https://github.com/codacy/codacy-stylelint/pull/27
- [x] SwiftLint https://github.com/codacy/codacy-swiftlint/pull/15
- [x] tailor
- [x] ~~TSQLLint~~

**Comment by ljmf00** [comment]
Hey @lolgab , just a quick mention here, TSQLLint integration does actually support timeout variable, because of the csharp seed. :wink:

**Comment by lolgab** [comment]
Thanks for the hint @ljmf00
