### ISSUE TITLE
PyLint (Python 3) patterns running when disabled on the UI

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#257]
The PyLint (Python3) pattern line-too-long (C0301) is running on projects even if disabled<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9205'>Zendesk ticket #9205</a>)<br>gz#9205</i>

**Comment by paulacodacy** [comment]
Pattern 'line-too-long (C0301)' from PyLint (Python 3) is set with parameter '120', but gives Line too long (105/100) after commit/pull request analysis.

**Comment by lolgab** [comment]
It should be fixed now. Try to reanalyse the commit please.

**Comment by rahulkumariitd57** [comment]
Yes, Verified. It's working now.

**Comment by lolgab** [comment]
Perfect 👌
Thank you for pointing it out. 

Lorenzo
