### ISSUE TITLE
[CY-2412] Add support to rubocop-airbnb

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#258]
Add support to rubocop-airbnb<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9206'>Zendesk ticket #9206</a>)<br>gz#9206</i>

**Comment by mrfyda** [comment]
@josemiguelmelo can you tackle this with codacy/codacy-meta#306?

**Comment by lolgab** [comment]
Blocked by https://github.com/airbnb/ruby/pull/169
