### ISSUE TITLE
Add support for yarn.lcok as an alternative to  npm-shrinkwrap.json to run node security

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#266]
Add support for yarn.lcok as an alternative to npm-shrinkwrap.json to run node security<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9237'>Zendesk ticket #9237</a>)<br>gz#9237</i>

**Comment by mrfyda** [comment]
nsp is deprecated and hasn't been updated.
we're removing nsp in #275
