### ISSUE TITLE
Remove tools that don't expose patterns to the Codacy UI

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#268]
We had this particular problem with codacy-prospector. Other tools facing this issue now:
- nsp is a security tool to detect vulnerable dependencies that is not maintained and has not been updated for several years
- with revive we offer a pattern by pattern replacement for golint, which has remained unversioned and outdated for years
- scsslint has also been deprecated and out of the two replacements, stylelint and sasslint, we already support the first for some time

Given that all these tools provide a bad experience to users we should be comfortable with this despite the fact that some users might be still using them.

Let’s just make sure we communicate this!

**Comment by mrfyda** [comment]
:D
