### ISSUE TITLE
Issues on Pylint due to imports should not be flagged in Codacy

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#271]
The patterns regarding imports should not be running in Codacy as they always cause false positives<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9304'>Zendesk ticket #9304</a>)<br>gz#9304</i>

- We could add a patterns blacklist as we do in codacy-eslint

**Comment by mrfyda** [comment]
@IGFCoimbra can you add more details here?
