### ISSUE TITLE
Review contributed updates to codacy/codacy-stylelint

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#28]
<p>We had some updates being contributed by users that need to be reviewed and integrated.<br/>
<a href="https://github.com/codacy/codacy-stylelint/pulls:" class="external-link" rel="nofollow">https://github.com/codacy/codacy-stylelint/pulls:</a></p>
<ul>
	<li><a href="https://github.com/codacy/codacy-stylelint/pull/7" class="external-link" rel="nofollow">https://github.com/codacy/codacy-stylelint/pull/7</a></li>
	<li><a href="https://github.com/codacy/codacy-stylelint/pull/6" class="external-link" rel="nofollow">https://github.com/codacy/codacy-stylelint/pull/6</a></li>
	<li><a href="https://github.com/codacy/codacy-stylelint/pull/5" class="external-link" rel="nofollow">https://github.com/codacy/codacy-stylelint/pull/5</a></li>
</ul>

**Comment by Laracodacy** [comment]
Duplicated from #169
