### ISSUE TITLE
[codacy-coverage-reporter] Support Account Token authentication

### ISSUE THREAD

**Issue by caiofralmeida** [codacy/codacy-meta#284]
### The plugin does not support account token

We are automating our pipeline and have added a step to automatically send application coverage to Codacy, the use of Account Token makes this integration simpler as it is not necessary to configure a token for each application. As I understand the code, this scala plugin does not yet support Account Token as the plugin in nodejs https://github.com/codacy/node-codacy-coverage#account-token.

Is it possible to help us with this Account Token implementation for this scala plugin?

### Are you looking for help?
Yes

**Comment by mrfyda** [comment]
I'm moving this request to codacy-coverage-reporter as we are deprecating sbt-codacy-coverage.

**Comment by caiofralmeida** [comment]
Thank you @mrfyda

**Comment by mrfyda** [comment]
@franciscodua can you comment here the version that includes this?

**Comment by lolgab** [comment]
We added Account token authentication. Could you try the new feature and let us know if your use case is covered?
Thank you.
Lorenzo
