### ISSUE TITLE
Add deprecation notice to deprecated coverage report tools

### ISSUE THREAD

**Issue by franciscodua** [codacy/codacy-meta#302]
Codacy deprecated most of its coverage report tools.
We now support a single [report tool](https://github.com/codacy/codacy-coverage-reporter).
We should give some sort of an indication to people using the old tools that these are deprecated.

**Acceptance Criteria:**
* When running old coverage report tools, users are notified these are deprecated

**Comment by lolgab** [comment]
We could add deprecated notices on npm and other package managers.
