### ISSUE TITLE
[CY-2448] False positive delivered by Sonar c# rule "Parameter names used into ArgumentException constructors should match an existing one"

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#316]
One of the definition set by Sonar c# rule "Parameter names used into ArgumentException constructors should match an existing one" is:

The rule won't raise an issue if the parameter name is not a constant value (inline declaration, nameof() or const variable).

Although, when the only given argument is nameof(), an issue is thrown and therefore it's possible to be a false positive.

Please check internal zendesk ticket for more details.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9543'>Zendesk ticket #9543</a>)<br>gz#9543</i>

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
