### ISSUE TITLE
Doublecheck if the update RSS list contains all the tools

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#325]

**Comment by josemiguelmelo** [comment]
- [x] coffeelint
- [x] checkstyle
- [x] eslint
- [x] pmdjava
- [x] pmd
- [x] jshint
- [x] phpmd
- [x] pylint
- [x] pylint-python3
- [x] brakeman
- [x] scalastyle
- [x] rubocop
- [x] find-sec-bugs
- [ ] findbugs
- [x] bandit
- [x] tailor
- [x] cppcheck
- [x] shellcheck
- [x] codesniffer
- [x] csslint
- [x] tslint
- [x] hadolint
- [x] sqlint
- [x] jackson-linter
- [ ] prospector
- [x] bundler-audit
- [x] stylelint
- [x] sonar-csharp
- [ ] sonar-visual-basic
- [x] detekt
- [ ] staticcheck
- [x] credo
- [x] flawfinder
- [x] remark-lint
- [x] swiftlint
- [x] psscriptanalyzer
- [x] ameba
- [x] spotbugs
- [x] tsqllint
- [ ] codenarc
- [ ] gorevive
- [ ] example-tool
