### ISSUE TITLE
Ignore option not being applied 

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#332]
A user reported that while using a configuration file the option to ignore an issue is not being followed by Codacy.

The user has the option:

```
<module name="JavadocVariable">
<property name="severity" value="ignore"/>
</module>
```

But the issue is appearing in the UI
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9664'>Zendesk ticket #9664</a>)<br>gz#9664</i>

**Comment by lolgab** [comment]
It was a bug in our tool. We correctly reproduced and solved.
Now we are pushing the new version in production.
I'll close this issue when the new version is live.
It will use Checkstyle 8.30 too
