### ISSUE TITLE
Error on Remark Lint

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#337]
We found that on some analysys Remark Lint is failing with the message

RemarkLint00:00:11
An error occurred during this step. Please, retry your analysis or contact support.

We made some tests and the tool seems to be failing depending on the patterns enabled.

Some of the patterns that seems to be causing the problem are:
Warn for autolinks without protocol.
Warn for too many consecutive blank lines.
Warn for violating emphasis markers.

https://app.codacy.com/gh/codacy/docs/commit?bid=17190923&cid=452041473<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9699'>Zendesk ticket #9699</a>)<br>gz#9699</i>

**Comment by franciscodua** [comment]
This problem was related to filenames with single quotes (`'`). It's now fixed on the Cloud offer
