### ISSUE TITLE
Coverage file being flagged as empty

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#340]
A user reported that while uploading the coverage for a project this error message appeared:

https://i.imgur.com/EA7X7h9.png

The user shared the coverage report that is being uploaded and it has information<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9723'>Zendesk ticket #9723</a>)<br>gz#9723</i>

**Comment by franciscodua** [comment]
It seems the PHPUnit version you are using outputs an XML format that is not supported by the coverage reporter.

As a workaround you can replace the flag `--coverage-xml` with `--coverage-clover` and use the clover format to send your coverage.
For more information check their [documentation](https://phpunit.readthedocs.io/en/9.1/textui.html).

We will either update our documentation to make this explicit (XML format is supported for versions <=4), or we will update the version we support.

Thanks for the feedback and let us know if this is an acceptable workaround for you.
