### ISSUE TITLE
Prettier 2.0 not supported

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#344]
Add support to prettier 2.0

https://prettier.io/blog/2020/03/21/2.0.0.html

<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9831'>Zendesk ticket #9831</a>)<br>gz#9831</i>

**Comment by lolgab** [comment]
We don't run Prettier directly but we use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) .
It still uses Prettier 1.x, as you can see [here](https://github.com/prettier/eslint-plugin-prettier/blob/185b1064d3dd674538456fb2fad97fbfcde49e0d/package.json#L46).

**Comment by lolgab** [comment]
Blocked by https://github.com/prettier/eslint-plugin-prettier/pull/281
