### ISSUE TITLE
[CY-2429] Support Terraform (Checkov)

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#35]

**Comment by lolgab** [comment]
A possible candidate tool is [Checkov](https://github.com/bridgecrewio/checkov), a Terraform linter recently released as Open Source (Apache2 licensed)

**Comment by mrfyda** [comment]
Moved to productboard

**Comment by paulacodacy** [comment]
Hi @codacy/toss, can you share the results of the research to support Terraform, please? Namely, using the Checkov, as this has been requested by a customer. Thank you.
