### ISSUE TITLE
Same patterns have broken links on their documentation

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#361]
Users are reporting that the links on some of our documentation are broken

For this case the Codacy’s link is https://www.owasp.org/index.php/Top_10-2017_A10-Insufficient_Logging%26Monitoring

While the actual link is
https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A10-Insufficient_Logging%252526Monitoring

Attachments:<br/> [inline-comment-image-1](https://downloads.intercomcdn.com/i/o/201011792/3c09b9d2df75d2863aa19dce/Annotation+2020-04-16+082828.png)<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9993'>Zendesk ticket #9993</a>)<br>gz#9993</i>

**Comment by lolgab** [comment]
This is a problem of sonar-dotnet.
Opened a PR to fix it in the original repository: https://github.com/SonarSource/sonar-dotnet/pull/3297

**Comment by lolgab** [comment]
The Sonar team is aware of the problem. When they will solve it we will have it fixed with a tool update.
I'm closing this issue then.
