### ISSUE TITLE
[CY-2461] Spike: What prevents unsupported language files from being analysed?

### ISSUE THREAD

**Issue by mrfyda** [codacy/codacy-meta#374]
Issues from a custom tool might report on files of any language.
For the user reporting the issues, it should not concern what languages are supported by Codacy.

Find out all mechanism preventing a file received in the remote results API from being analysed.

Check:
- [x] Does the worker manager filter anything or avoids running workers?
- [x] Check if worker skips execution if changed files are not supported
- [x] Check if worker filters results by file types

**Comment by josemiguelmelo** [comment]
We have unsupported languages filtered in two places:

- TaskSupplier -> on precog task, we are grouping files per task/algorithm and filtering out files that are not supported by the algorithm
- AnalysisReportRules -> when fetching remote results (before processing it), those results are filtered for the files that are being analysed by the algorithm. These files come from the filter mentioned above

**Comment by mrfyda** [comment]
could we ignore the files coming from the filter in TaskSupplier and rely on those specified on a remote results report? what would happen if a report had a file that did not belong to that list? what would have to change so that we display issues for that file?

**Comment by lolgab** [comment]
> could we ignore the files coming from the filter in TaskSupplier and rely on those specified on a remote results report?

Which files should we display on the files page? All of them? The ones that have issues? Or the supported files only?

> what would happen if a report had a file that did not belong to that list?

At the moment engine filters out all issues with unknown extensions.
