### ISSUE TITLE
Support WordPress VIP on PHP CodeSniffer

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#385]
https://wpvip.com/documentation/how-to-install-php-code-sniffer-for-wordpress-vip/<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10474'>Zendesk ticket #10474</a>)<br>gz#10474</i>

**Comment by josemiguelmelo** [comment]
The plugin was added to Codesniffer. It should be already running in production.
