### ISSUE TITLE
[CY-2408] ESlint Patterns without parameter to select different options

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#388]
A customer has kindly checked and gave us a list of patterns in ESlint that doesn't have parameters to select the different supported options:

```
Enforce arrow function as callback
Enforce using const
Func call spacing 
Implicit arrow linebreak
Import: Extensions
Key spacing
Max len
No console
No extra boolean cast 
No multiple empty lines
No unused vars 
Nonblock statement body position 
Object curly newline 
Padded blocks 
Prohibit return in else 
Prohibit square-bracket notation 
Require space around arrow function's
Semi
Space before blocks 
Space before function paren
Spaced comment
```

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally

**Comment by machadoit** [comment]
Hi @KsuBurn,

Thank you for providing that list. At the moment we don't want to add those parameters in our codacy-eslint itself, we will be evaluating contributing upstream on ESLint itself so we can obtain those automatically on our scripts
