### ISSUE TITLE
Spike: Investigate how the CLI works today

### ISSUE THREAD

**Issue by franciscodua** [codacy/codacy-meta#396]
What are the current problems with our CLI? What can we reuse or improve?
What are the necessary steps to perform the analysis? (register them)
Understand the whole process and propose changes/improvements

**Acceptance criteria:**
- Current CLI limitations are documented
- Analysis steps are documented (steps descriptions and where they happen - CLI vs Platform)
- Set of changes are aligned with the team (create new backlog tasks)

**Comment by pauloribeiro-codacy** [comment]
Hi @franciscodua, where can I see the conclusions from this task? Did you produce some kind of internal documentation?

Thanks!

**Comment by franciscodua** [comment]
The assignee is @josemiguelmelo.
Can you share with Paulo your findings?

**Comment by pauloribeiro-codacy** [comment]
Sorry @franciscodua, I saw your name first! 😅

**Comment by josemiguelmelo** [comment]
Hi @pauloribeiro-codacy,

I created an internal document with the CLI functioning and the parts that we should change. Sent it to you.
