### ISSUE TITLE
[CY-2476] Broken link in pattern's documentation

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#404]
Some patterns on Stylelint 13.5.0 have broken links for documentation. 

Some examples are:
 
Specify indentation
Specify lowercase or uppercase for function names<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10665'>Zendesk ticket #10665</a>)<br>gz#10665</i>

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
