### ISSUE TITLE
[CY-2403] Add support to angular-eslint/eslint-plugin

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#419]
https://www.npmjs.com/package/@angular-eslint/eslint-plugin
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10954'>Zendesk ticket #10954</a>)<br>gz#10954</i>

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
