### ISSUE TITLE
[CY-2418] Add support for fimbullinter

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#423]
[https://github.com/fimbullinter/wotan](https://github.com/fimbullinter/wotan)  
  
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11040'>Zendesk ticket #11040</a>)<br>gz#11040</i>

**Comment by franciscodua** [comment]
Note: Still experimental https://github.com/fimbullinter/wotan#semantic-versioning-semver-policy. Might be too soon to support this tool

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
