### ISSUE TITLE
[CY-2439] Go Security Dashboard

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#424]
Add support for Go's security issues

https://github.com/securego/gosec<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11017'>Zendesk ticket #11017</a>)<br>gz#11017</i>

**Comment by josemiguelmelo** [comment]
Hi,

The tool is implemented as a client side tool: https://github.com/codacy/codacy-gosec
