### ISSUE TITLE
Sonar c# analysis failure: The failure log only shows found patterns issues

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#425]
User's commit doesn't finish Sonar C# analysis and it gives the following error log structure:

```
KubernetesDockerRunner: Container for codacy/codacy-sonar-csharp:3.4.12 exited with non-zero code 2
{"filename":"path/example_file","message":"Make 'dataManageClass' 'readonly'.","patternId":"S2933","line":16}
...

```
The log contains the found issues from the patterns and this could be related with the excessive analysis time.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11046'>Zendesk ticket #11046</a>)<br>gz#11046</i>

**Comment by franciscodua** [comment]
The problem reported is a timeout.

Since we had some reports about timeouts now, with Sonar C# we created an exception and decreased the number of files analyzed at a time in order to reduce the likelihood of timeouts.

This seems to solve the problem with the open ticket so I'll close this issue
