### ISSUE TITLE
[CY-2409] Update tslint to 6.**.**

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#430]
TSLint has relessed a new major version:

https://github.com/palantir/tslint/releases<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11093'>Zendesk ticket #11093</a>)<br>gz#11093</i>

**Comment by dangowans** [comment]
I do see that tslint has been marked as deprecated if favour of eslint.  If that's the case, perhaps this issue should just be closed instead.

https://github.com/palantir/tslint

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
