### ISSUE TITLE
[CY-2449] Checkstyle failure: ${config_loc} has not been set

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#433]
User's repository has a commit failing in Checkstyle, the most important part of the log is:
`Caused by: org.xml.sax.SAXException: Property ${config_loc} has not been set`

The config file checkstyle.xml has:
`<property name="file" value="${config_loc}/suppressions.xml"/>`

Locally and in CI/CD pipleline, the user doesn't have issues when running version 8.32 of the tool. 

For more details, please check the internal ticket.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11284'>Zendesk ticket #11284</a>)<br>gz#11284</i>

**Comment by josemiguelmelo** [comment]
Hi,

Checkstyle plugin defines a `config_loc` property that can be used in Checkstyle configuration files to define paths to other configuration files. We are now defining this property and the bug should be fixed in production.
