### ISSUE TITLE
[CY-2474] False positive from Sonar C# pattern "Methods and properties that don't access instance data should be static"

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#435]
False positive from Sonar C# pattern "Methods and properties that don't access instance data should be static", because this pattern also delivers issues on interface/abstract class implementations, please check a particular issue in the internal ticket.

I've also run on cli for the example an example file and as in the UI, it also delivered:

> Found [Info] `Make 'Register' a static method.` in MapsterRegister.cs:15 (SonarCSharp_S2325)

So, it seems the original official Sonar C# tool also has this issue and it has already been reported in the past on their repo: https://github.com/SonarSource/sonar-dotnet/issues/1068.
How should we proceed with this, maybe worth reopening the issue there?<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11330'>Zendesk ticket #11330</a>)<br>gz#11330</i>

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
