### ISSUE TITLE
Default Prospector config is causing conflicts

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#442]
Prospector's pattern  "pep257 tool" seems to have conflicting rules being checked when it is active

Attachments:<br/> [Screen Shot 2020-07-10 at 17.00.46.png](https://codacy.zendesk.com/attachments/token/lqbkyFqmJ8jAiONll6p2WhrgU/?name=Screen+Shot+2020-07-10+at+17.00.46.png)<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11310'>Zendesk ticket #11310</a>)<br>gz#11310</i>

**Comment by lolgab** [comment]
This is a known issue of prospector. Sadly we can't solve it.
You have to choose your preferred pattern and disable the other using a configuration file.
For example you can have a `.prospector.yml` like this:
```yml
pep257:
  disable:
    - D213
```

**Comment by lolgab** [comment]
I'm closing the issue for now.
Feel free to reopen it if you still have problems with it.
