### ISSUE TITLE
[CY-2459] Support CppCoreGuidelines: cppcoreguidelines-pro-type-member-init

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#451]
Support the above pattern for CPP analysis, more info in:
- https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-member-init.html
- https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Pro-type-memberinit
_Type.6: Always initialize a member variable: always initialize, possibly using default constructors or default member initializers._

**Comment by franciscodua** [comment]
I'll close this issue as we're tracking it internally

**Comment by oneiric** [comment]
Hi @paulacodacy and @franciscodua ,
Is there any progress for this feature support?

**Comment by lolgab** [comment]
@oneiric We should already support it, it is [listed in Codacy UI](https://github.com/codacy/codacy-clang-tidy/blob/8678e2286764de2cb9f51b40743d8b4b71070b27/docs/patterns.json#L1482).
Did you find it not working? In case you do could you file a reproduction?

**Comment by oneiric** [comment]
Thanks, I will check our project.
