### ISSUE TITLE
Support Clojure

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#71]
gz#7714

**Comment by lolgab** [comment]
Public comment from Codacy Team in <a href='https://codacy.zendesk.com/agent/tickets/7714'>Zendesk ticket #7714</a>:<br><br>Hi Andrea,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going here https://github.com/codacy/codacy-meta/issues/71.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

**Comment by mrfyda** [comment]
Moved to productboard

**Comment by anwood** [comment]
Any update here? Does moving to 'productboard' mean it might get added?

**Comment by mrfyda** [comment]
hey @anwood 

productboard is the tool we're using to centralize user feedback. unfortunately, at this time it's something we can easily share openly.

however, you can see what we're working and what's planned on our public roadmap: http://roadmap.codacy.com/
