### ISSUE TITLE
Update the version of Prospector

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#81]
1.1.6.2.

gz#6420

**Comment by lolgab** [comment]
Public comment from Codacy Team in <a href='https://codacy.zendesk.com/agent/tickets/6420'>Zendesk ticket #6420</a>:<br><br>Hi Karl,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going here https://github.com/codacy/codacy-meta/issues/81.

This is part of our initiative to move all support requests relating to adding and improving of tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

**Comment by Laracodacy** [comment]
Check #42 once the tool is updated.
