### ISSUE TITLE
Crystal Tool integration

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#84]
We had feedback from a user indicating the following:

<p>I followed the steps described in Tool Development Guide <a href="https://support.codacy.com/hc/en-us/articles/207994725-Tool-Developer-Guide" class="external-link" rel="nofollow">https://support.codacy.com/hc/en-us/articles/207994725-Tool-Developer-Guide</a> and prepared a new integration project for the static analysis tool I own and which is named Ameba. This is the utility for Crystal programming language and is basically only the one tool publicly available in this category for Crystal.</p>

<p>Related links:</p>

<ul>
	<li><a href="https://github.com/veelenga/codacy-ameba" class="external-link" rel="nofollow">https://github.com/veelenga/codacy-ameba</a> <a href="https://github.com/veelenga/codacy-ameba" class="external-link" rel="nofollow">https://github.com/veelenga/codacy-ameba</a></li>
	<li><a href="https://github.com/veelenga/ameba" class="external-link" rel="nofollow">https://github.com/veelenga/ameba</a> <a href="https://github.com/veelenga/ameba" class="external-link" rel="nofollow">https://github.com/veelenga/ameba</a></li>
	<li><a href="https://crystal-lang.org/" class="external-link" rel="nofollow">https://crystal-lang.org/</a> <a href="https://crystal-lang.org/" class="external-link" rel="nofollow">https://crystal-lang.org/</a></li>
</ul>

He is also happy to contribute with this process if required.

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/6147'>Zendesk ticket #6147</a>:<br><br>Hi Vitalii,

I am reaching out to let you know that this support ticket is being migrated to Github and you will now be able to view and keep tabs on the ticket progress by going to https://github.com/codacy/codacy-meta/issues/84.

This is part of our initiative to move all support requests relating to adding and improving tool/languages to Github for improved visibility and as a first step towards making our roadmaps public.

To be notified of new releases,  you can subscribe to our product updates by clicking on the follow button here.

Please let me know if you have any questions.

Regards,
Ivo

Support Engineer at Codacy

**Comment by Laracodacy** [comment]
Already addressed, we support Crystal - Ameba v0.8.1.
