### ISSUE TITLE
PHP Code Sniffer unnamed patterns

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#85]
We believe these are the only 2:

![Screen Shot 2019-08-12 at 14 09 17](https://user-images.githubusercontent.com/36406414/62867266-d016f980-bd0a-11e9-92a5-e0ec2eec9a11.png)

gz#6122

gz#7093

**Comment by Laracodacy** [comment]
We will first address a missing update for PHP CodeSniffer and understand if this problem still remains. https://github.com/codacy/codacy-meta/issues/24
