### ISSUE TITLE
Support Scalafix's Disable rule

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#86]
<p>We need to know if it's possible for Scalameta Pro to support something as  Scalafix's flexible Disable rule: <br/>
<a href="https://github.com/scalaz/scalazzi/blob/master/scalafix.conf" class="external-link" rel="nofollow">https://github.com/scalaz/scalazzi/blob/master/scalafix.conf</a> </p>
<br><br><i>(related to <a href='https://codacy.zendesk.com/agent/tickets/4489'>Zendesk ticket #4489</a>)<br>gz#4489</i>

**Comment by mrfyda** [comment]
No longer relevant.
