### ISSUE TITLE
[FT-5901] Update plugin: eslint-plugin-cypress

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#89]
<p>-We have enterprise costumer (
    <span class="jira-issue-macro resolved" data-jira-key="FT-5819" >
                <a href="https://codacy.atlassian.net/browse/FT-5819" class="jira-issue-macro-key issue-link"  title="Analysis failing due to permission error" >
            <img class="icon" src="https://codacy.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />
            FT-5819
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Resolved</span>
            </span>
) that had some problems, but now seems to be running. HOWEVER, now that they have analysis, some of those fail because of the "ESLint couldn't find the plugin "eslint-plugin-cypress""</p>

<p>Task: Add <a href="https://github.com/cypress-io/eslint-plugin-cypress" class="external-link" rel="nofollow">https://github.com/cypress-io/eslint-plugin-cypress</a> to <a href="https://github.com/codacy/codacy-eslint-" class="external-link" rel="nofollow">https://github.com/codacy/codacy-eslint-</a></p>

<p><a href="https://github.com/codacy/codacy-eslint/pull/128/files" class="external-link" rel="nofollow">https://github.com/codacy/codacy-eslint/pull/128/files</a></p>

**Comment by gjsduarte** [comment]
This has been done in https://github.com/codacy/codacy-eslint/pull/133.
